project_id = "ugyvgtzsvhmcohnooxqp"

[functions.transcribe]
verify_jwt = false

[functions.plenario-cron]
verify_jwt = false

[functions.hls-proxy]
verify_jwt = false

[functions.scrape-plenario]
verify_jwt = false

[functions.scrape-politicians]
verify_jwt = false
